#!/bin/bash
#
# Jellyfin + rffmpeg Setup Module for Transcodarr
#
# This script generates all configuration files LOCALLY in an output folder.
# You then copy these files to your Synology/server.
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/../output"

# Generate SSH key pair locally
generate_ssh_key() {
    local ssh_dir="${OUTPUT_DIR}/rffmpeg/.ssh"
    local key_file="${ssh_dir}/id_rsa"

    mkdir -p "$ssh_dir"

    if [[ -f "$key_file" ]]; then
        if gum confirm "SSH key already exists in output folder. Regenerate?"; then
            rm -f "$key_file" "${key_file}.pub"
        else
            gum style --foreground 46 "✓ Using existing SSH key"
            return 0
        fi
    fi

    gum style --foreground 212 "Generating SSH key pair..."
    ssh-keygen -t ed25519 -f "$key_file" -N "" -C "transcodarr-rffmpeg"

    chmod 600 "$key_file"
    chmod 644 "${key_file}.pub"

    gum style --foreground 46 "✓ SSH key pair generated in output/rffmpeg/.ssh/"
}

# Create rffmpeg configuration
create_rffmpeg_config() {
    local mac_ip="$1"
    local mac_user="$2"
    local config_file="${OUTPUT_DIR}/rffmpeg/rffmpeg.yml"

    mkdir -p "$(dirname "$config_file")"

    cat > "$config_file" << EOF
# Transcodarr - rffmpeg Configuration
# Generated by Transcodarr Installer
#
# This file goes in: /config/rffmpeg/rffmpeg.yml (inside Jellyfin container)
# On Synology that's: /volume1/docker/jellyfin/rffmpeg/rffmpeg.yml

rffmpeg:
    logging:
        log_to_file: true
        logfile: "/config/log/rffmpeg.log"
        debug: false

    directories:
        state: "/config/rffmpeg"
        persist: "/config/rffmpeg/persist"
        owner: abc
        group: abc

    remote:
        user: "${mac_user}"
        persist: 300
        args:
            - "-o"
            - "StrictHostKeyChecking=no"
            - "-o"
            - "UserKnownHostsFile=/dev/null"
            - "-i"
            - "/config/rffmpeg/.ssh/id_rsa"

    commands:
        ssh: "/usr/bin/ssh"
        # FFmpeg paths on Mac (Homebrew on Apple Silicon)
        ffmpeg: "/opt/homebrew/bin/ffmpeg"
        ffprobe: "/opt/homebrew/bin/ffprobe"
        # Fallback to local ffmpeg if all remotes fail
        fallback_ffmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
        fallback_ffprobe: "/usr/lib/jellyfin-ffmpeg/ffprobe"
EOF

    gum style --foreground 46 "✓ rffmpeg.yml created in output/rffmpeg/"
}

# Create Docker Compose file
create_docker_compose() {
    local mac_ip="$1"
    local nas_ip="$2"
    local cache_path="${3:-/volume1/docker/jellyfin/cache}"
    local jellyfin_config="${4:-/volume1/docker/jellyfin}"
    local compose_file="${OUTPUT_DIR}/docker-compose.yml"
    local changes_file="${OUTPUT_DIR}/EXISTING_JELLYFIN_CHANGES.md"

    # Create full docker-compose for new installs
    cat > "$compose_file" << EOF
# Transcodarr - Jellyfin with rffmpeg
# FOR NEW INSTALLATIONS: Copy this file to your Synology/server
# ALREADY HAVE JELLYFIN? See EXISTING_JELLYFIN_CHANGES.md instead!

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000          # ← Change to your user ID (run 'id' on Synology)
      - PGID=1000          # ← Change to your group ID
      - TZ=Europe/Amsterdam
      - JELLYFIN_PublishedServerUrl=${nas_ip}
      - UMASK=022
      # Enable rffmpeg for distributed transcoding
      - DOCKER_MODS=linuxserver/mods:jellyfin-rffmpeg
      - FFMPEG_PATH=/usr/local/bin/ffmpeg
    volumes:
      - ${jellyfin_config}:/config                 # ← Jellyfin config folder
      - /volume1/data/media:/data/media            # ← Your media folder
      - ${cache_path}:/config/cache                # ← Transcode cache
    ports:
      - 8096:8096/tcp      # HTTP web interface
      - 8920:8920/tcp      # HTTPS (optional)
      - 7359:7359/udp      # Client discovery
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
EOF

    # Create guide for existing Jellyfin users
    cat > "$changes_file" << EOF
# Already Have Jellyfin? Here's What to Change

You don't need to replace your entire docker-compose.yml!
Just add a few lines to your EXISTING Jellyfin configuration.

---

## Step 1: Add these environment variables

Add these 2 lines to your Jellyfin's \`environment:\` section:

\`\`\`yaml
environment:
  # ... your existing variables ...

  # ADD THESE TWO LINES:
  - DOCKER_MODS=linuxserver/mods:jellyfin-rffmpeg
  - FFMPEG_PATH=/usr/local/bin/ffmpeg
\`\`\`

**What do they do?**
- \`DOCKER_MODS\` → Installs rffmpeg in the container (enables distributed transcoding)
- \`FFMPEG_PATH\` → Tells Jellyfin to use rffmpeg instead of regular ffmpeg

---

## Step 2: Check your cache volume (important!)

For distributed transcoding to work, your Mac writes transcoded files to a cache folder.
Jellyfin reads from this same folder. Both need access to the SAME folder.

**Check if you have a cache volume mapped:**

\`\`\`yaml
volumes:
  - /path/to/config:/config
  - /path/to/media:/data/media
  # Do you have this? If not, ADD IT:
  - ${cache_path}:/config/cache
\`\`\`

**If you already have a cache volume** (like \`/volume1/docker/jellyfin/cache:/config/cache\`), you're good!
Just make sure the Mac can access this folder via NFS.

**If you don't have a cache volume**, add one:
\`\`\`yaml
volumes:
  # ... your existing volumes ...
  - ${cache_path}:/config/cache    # ← ADD THIS
\`\`\`

Then create the folder on your NAS:
\`\`\`bash
mkdir -p ${cache_path}
\`\`\`

---

## Step 3: Enable NFS access to the cache folder

Your Mac needs to read/write to the cache folder via NFS.

On Synology:
1. Go to **Control Panel → File Services → NFS → Enable NFS**
2. Go to **Control Panel → Shared Folder → [your jellyfin folder] → Edit → NFS Permissions**
3. Add a rule:
   - Hostname: Your Mac's IP or \`*\`
   - Privilege: Read/Write
   - Squash: Map all users to admin

---

## Step 4: Copy the rffmpeg configuration

Copy the generated files to your Jellyfin config folder:

\`\`\`bash
# On your server, create the rffmpeg folder:
mkdir -p /volume1/docker/jellyfin/rffmpeg/.ssh

# Copy the files (from this computer):
scp -r output/rffmpeg/* YOUR_USER@${nas_ip}:/volume1/docker/jellyfin/rffmpeg/

# Set permissions:
ssh YOUR_USER@${nas_ip} "chmod 600 /volume1/docker/jellyfin/rffmpeg/.ssh/id_rsa"
\`\`\`

---

## Step 5: Restart Jellyfin

\`\`\`bash
docker compose down
docker compose up -d
\`\`\`

Wait ~30 seconds for the container to fully start (it needs to install rffmpeg).

---

## Step 6: Add your Mac as transcode node

\`\`\`bash
docker exec jellyfin rffmpeg add ${mac_ip} --weight 2
\`\`\`

Verify:
\`\`\`bash
docker exec jellyfin rffmpeg status
\`\`\`

---

## Example: Before and After

**BEFORE (your existing docker-compose.yml):**
\`\`\`yaml
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /path/to/config:/config
      - /path/to/media:/data/media
    ports:
      - 8096:8096
\`\`\`

**AFTER (with rffmpeg added):**
\`\`\`yaml
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DOCKER_MODS=linuxserver/mods:jellyfin-rffmpeg    # ← ADD THIS
      - FFMPEG_PATH=/usr/local/bin/ffmpeg                 # ← ADD THIS
    volumes:
      - /path/to/config:/config
      - /path/to/media:/data/media
    ports:
      - 8096:8096
\`\`\`

That's all you need to change!
EOF

    gum style --foreground 46 "✓ docker-compose.yml created in output/"
    gum style --foreground 46 "✓ EXISTING_JELLYFIN_CHANGES.md created (for existing setups)"
}

# Create a simple README with step-by-step instructions
create_readme() {
    local mac_ip="$1"
    local mac_user="$2"
    local nas_ip="$3"
    local nas_user="${4:-admin}"
    local cache_path="${5:-/volume1/docker/jellyfin/cache}"
    local jellyfin_config="${6:-/volume1/docker/jellyfin}"
    local readme_file="${OUTPUT_DIR}/SETUP_INSTRUCTIONS.md"
    local public_key=""

    if [[ -f "${OUTPUT_DIR}/rffmpeg/.ssh/id_rsa.pub" ]]; then
        public_key=$(cat "${OUTPUT_DIR}/rffmpeg/.ssh/id_rsa.pub")
    fi

    cat > "$readme_file" << EOF
# Transcodarr Setup Instructions

Generated configuration for:
- **Mac IP:** ${mac_ip}
- **Mac Username:** ${mac_user}
- **NAS/Server IP:** ${nas_ip}

---

## Step 1: Setup SSH on your Mac (${mac_ip})

Your Mac needs to accept SSH connections from the Jellyfin server.

### 1.1 Enable Remote Login on Mac

1. Open **System Settings** on your Mac
2. Go to **General** → **Sharing**
3. Turn ON **Remote Login**
4. Make sure your user (${mac_user}) has access

### 1.2 Add the SSH key to your Mac

Run this command **on your Mac**:

\`\`\`bash
mkdir -p ~/.ssh
echo "${public_key}" >> ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
\`\`\`

Or manually:
1. Open Terminal on your Mac
2. Run: \`nano ~/.ssh/authorized_keys\`
3. Paste this key on a new line:
   \`${public_key}\`
4. Save (Ctrl+O, Enter, Ctrl+X)

---

## Step 2: Copy files to your Synology/Server

Copy the generated files to your Synology. You can use Finder, SCP, or the Synology web interface.

### Files to copy:

| Local file | Copy to on Synology |
|------------|---------------------|
| \`output/rffmpeg/rffmpeg.yml\` | \`${jellyfin_config}/rffmpeg/rffmpeg.yml\` |
| \`output/rffmpeg/.ssh/id_rsa\` | \`${jellyfin_config}/rffmpeg/.ssh/id_rsa\` |
| \`output/rffmpeg/.ssh/id_rsa.pub\` | \`${jellyfin_config}/rffmpeg/.ssh/id_rsa.pub\` |
| \`output/docker-compose.yml\` | Your Jellyfin compose folder |

### Using SCP (copy from your current computer to Synology):

\`\`\`bash
# First, create the folders on Synology:
ssh ${nas_user}@${nas_ip} "sudo mkdir -p ${jellyfin_config}/rffmpeg/.ssh"

# Then copy the files (run this on your LOCAL computer):
scp -r output/rffmpeg/* ${nas_user}@${nas_ip}:${jellyfin_config}/rffmpeg/
\`\`\`

💡 **TIP:** If you see "Are you sure you want to continue connecting?" type \`yes\` and press Enter.

### Set correct permissions (run ON Synology):

\`\`\`bash
sudo chmod 600 ${jellyfin_config}/rffmpeg/.ssh/id_rsa
sudo chmod 644 ${jellyfin_config}/rffmpeg/.ssh/id_rsa.pub
\`\`\`

---

## Step 3: Start Jellyfin

On your Synology/server, in the folder with docker-compose.yml:

\`\`\`bash
docker compose up -d
\`\`\`

Wait about 30 seconds for the container to fully start.

---

## Step 4: Add your Mac as a transcode node

Run this command **on your Synology** (or wherever Docker runs):

\`\`\`bash
docker exec jellyfin rffmpeg add ${mac_ip} --weight 2
\`\`\`

---

## Step 5: Verify it works

Check the status:

\`\`\`bash
docker exec jellyfin rffmpeg status
\`\`\`

You should see your Mac listed with "idle" state.

Test SSH connection:

\`\`\`bash
docker exec -u abc jellyfin ssh -o StrictHostKeyChecking=no -i /config/rffmpeg/.ssh/id_rsa "${mac_user}@${mac_ip}" "/opt/homebrew/bin/ffmpeg -version"
\`\`\`

If this shows FFmpeg version info, everything works!

---

## Troubleshooting

### "Permission denied" error
- Check that Remote Login is enabled on Mac
- Check that the SSH key is in ~/.ssh/authorized_keys on Mac
- Check file permissions on Synology: \`chmod 600 ${jellyfin_config}/rffmpeg/.ssh/id_rsa\`

### "Host marked as bad" in rffmpeg status
- Clear the state: \`docker exec -u abc jellyfin rffmpeg clear\`
- Re-add the Mac: \`docker exec jellyfin rffmpeg add ${mac_ip} --weight 2\`

### Mac not responding
- Make sure Mac doesn't go to sleep: System Settings → Energy → Prevent sleep
- Check Mac firewall allows SSH (port 22)

---

## Optional: Monitoring Setup (Prometheus + Grafana)

Want to see CPU/memory usage of your Macs? Follow these steps:

### Step 1: Install node_exporter on EACH Mac

Run this on every Mac that does transcoding:

\`\`\`bash
brew install node_exporter
brew services start node_exporter
\`\`\`

Verify it works: http://${mac_ip}:9100/metrics

### Step 2: Copy monitoring files to your server

Copy the entire \`monitoring/\` folder to your server:

\`\`\`bash
scp -r output/monitoring/* YOUR_USER@${nas_ip}:/volume1/docker/monitoring/
\`\`\`

### Step 3: Start Prometheus + Grafana

On your server:

\`\`\`bash
cd /volume1/docker/monitoring
sudo docker compose up -d
\`\`\`

### Step 4: Setup Grafana

1. Open http://${nas_ip}:3000
2. Login with admin / admin
3. Go to ⚙️ → Data sources → Add data source
4. Select "Prometheus"
5. Set URL to: http://prometheus:9090
6. Click "Save & test"

### Step 5: Import Dashboard

1. Click + → Import
2. Upload \`grafana-dashboard.json\` from the monitoring folder
3. Select your Prometheus data source
4. Click Import

Done! You should see your Mac's stats.

### Adding more Macs

Edit \`prometheus.yml\` and add more targets:

\`\`\`yaml
- targets: ['192.168.1.51:9100']
  labels:
    node: 'mac-2'
\`\`\`

Then restart: \`sudo docker restart prometheus\`
EOF

    gum style --foreground 46 "✓ SETUP_INSTRUCTIONS.md created in output/"
}

# Show summary
show_summary() {
    local mac_ip="$1"
    local mac_user="$2"
    local nas_ip="$3"
    local nas_user="$4"
    local jellyfin_config="$5"
    local cache_path="$6"
    local public_key=""

    if [[ -f "${OUTPUT_DIR}/rffmpeg/.ssh/id_rsa.pub" ]]; then
        public_key=$(cat "${OUTPUT_DIR}/rffmpeg/.ssh/id_rsa.pub")
    fi

    echo ""
    gum style --foreground 46 --border double --padding "1 2" \
        "✅ Configuration files generated!"

    echo ""
    gum style --foreground 212 "📁 Generated files are in: ${OUTPUT_DIR}/"
    echo ""
    gum style --foreground 252 "   output/"
    gum style --foreground 252 "   ├── docker-compose.yml              ← New Jellyfin install"
    gum style --foreground 252 "   ├── EXISTING_JELLYFIN_CHANGES.md    ← Already have Jellyfin? Read this!"
    gum style --foreground 252 "   ├── SETUP_INSTRUCTIONS.md           ← Full guide"
    gum style --foreground 252 "   ├── rffmpeg/"
    gum style --foreground 252 "   │   ├── rffmpeg.yml"
    gum style --foreground 252 "   │   └── .ssh/"
    gum style --foreground 252 "   │       ├── id_rsa"
    gum style --foreground 252 "   │       └── id_rsa.pub"
    gum style --foreground 252 "   └── monitoring/                     ← Optional"
    gum style --foreground 252 "       ├── docker-compose.yml"
    gum style --foreground 252 "       ├── prometheus.yml"
    gum style --foreground 252 "       └── grafana-dashboard.json"

    echo ""
    gum style --foreground 212 --border normal --padding "1 2" \
        "📋 WHAT TO DO NOW (you are on Synology)"

    echo ""
    gum style --foreground 226 "STEP 1: Copy files to Jellyfin config (run these here on Synology):"
    echo ""
    gum style --foreground 39 --border normal --padding "0 1" \
        "sudo mkdir -p ${jellyfin_config}/rffmpeg/.ssh ${cache_path}"
    echo ""
    gum style --foreground 39 --border normal --padding "0 1" \
        "sudo cp -a ${OUTPUT_DIR}/rffmpeg/. ${jellyfin_config}/rffmpeg/"
    echo ""
    gum style --foreground 39 --border normal --padding "0 1" \
        "sudo chown -R 911:911 ${jellyfin_config}/rffmpeg"

    echo ""
    gum style --foreground 226 "STEP 2: Restart Jellyfin (run here on Synology):"
    echo ""
    gum style --foreground 39 --border normal --padding "0 1" \
        "docker restart jellyfin"

    echo ""
    gum style --foreground 212 --border double --padding "1 2" \
        "STEP 3: NOW GO TO YOUR MAC" \
        "" \
        "Run the installer on your Mac:" \
        "  git clone https://github.com/JacquesToT/Transcodarr.git ~/Transcodarr" \
        "  cd ~/Transcodarr && ./install.sh" \
        "" \
        "Choose: First Time Setup → On the Mac"

    echo ""
    gum style --foreground 226 "STEP 4: Add SSH key to your Mac"
    gum style --foreground 252 "We can install the SSH key on your Mac from here (requires Mac password once)."
    echo ""

    if gum confirm "Install SSH key on Mac now? (you'll need to enter your Mac password)"; then
        echo ""
        gum style --foreground 212 "Connecting to Mac at ${mac_ip}..."
        gum style --foreground 252 "Enter your Mac password when prompted:"
        echo ""

        # Run the SSH key installation command on the Mac
        if ssh -o StrictHostKeyChecking=accept-new "${mac_user}@${mac_ip}" "mkdir -p ~/.ssh && echo '${public_key}' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh"; then
            echo ""
            gum style --foreground 46 "✅ SSH key installed on Mac!"
        else
            echo ""
            gum style --foreground 196 "❌ Failed to install SSH key. You can do it manually:"
            gum style --foreground 39 --border normal --padding "0 1" \
                "mkdir -p ~/.ssh && echo '${public_key}' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
        fi
    else
        echo ""
        gum style --foreground 252 "Run this command ON YOUR MAC after Mac setup:"
        echo ""
        gum style --foreground 39 --border normal --padding "0 1" \
            "mkdir -p ~/.ssh && echo '${public_key}' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
    fi

    echo ""
    gum style --foreground 226 "STEP 5: Add Mac to rffmpeg (after Mac setup is complete):"
    echo ""

    # Check if rffmpeg is available in the Jellyfin container
    if docker exec jellyfin ls /usr/local/bin/rffmpeg &>/dev/null; then
        gum style --foreground 46 "✅ rffmpeg mod detected in Jellyfin container"
        echo ""
        gum style --foreground 39 --border normal --padding "0 1" \
            "docker exec jellyfin rffmpeg add ${mac_ip} --weight 2"
        echo ""
        gum style --foreground 39 --border normal --padding "0 1" \
            "docker exec jellyfin rffmpeg status"
    else
        gum style --foreground 196 "⚠️  rffmpeg NOT found in Jellyfin container!"
        echo ""
        gum style --foreground 252 "Your Jellyfin container needs the rffmpeg mod. Add these environment variables:"
        echo ""
        gum style --foreground 39 "  DOCKER_MODS=linuxserver/mods:jellyfin-rffmpeg"
        gum style --foreground 39 "  FFMPEG_PATH=/usr/local/bin/ffmpeg"
        echo ""
        gum style --foreground 252 "Then recreate the container:"
        gum style --foreground 39 "  docker compose down && docker compose up -d"
        echo ""
        gum style --foreground 252 "Or via Container Manager: Settings → Environment → Add variables"
        echo ""
        gum style --foreground 252 "After restarting, wait 30 seconds and run:"
        gum style --foreground 39 --border normal --padding "0 1" \
            "docker exec jellyfin rffmpeg add ${mac_ip} --weight 2"
    fi

    echo ""
    gum style --foreground 252 "For detailed instructions, read: ${OUTPUT_DIR}/SETUP_INSTRUCTIONS.md"
}

# Create monitoring configuration files
create_monitoring_config() {
    local mac_ip="$1"
    local nas_ip="$2"
    local monitoring_dir="${OUTPUT_DIR}/monitoring"

    mkdir -p "$monitoring_dir"

    # Create prometheus.yml
    cat > "$monitoring_dir/prometheus.yml" << EOF
# Prometheus Configuration for Transcodarr
# Copy this file to your server: /volume1/docker/monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Transcode Nodes (Macs with VideoToolbox)
  # Add ALL your Macs here!
  - job_name: 'transcode-nodes'
    static_configs:
      - targets: ['${mac_ip}:9100']
        labels:
          node: 'mac-1'
      # Add more Macs like this:
      # - targets: ['192.168.1.51:9100']
      #   labels:
      #     node: 'mac-2'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop
EOF

    # Create docker-compose.yml for monitoring
    cat > "$monitoring_dir/docker-compose.yml" << EOF
# Monitoring Stack for Transcodarr
# Copy this file to your server: /volume1/docker/monitoring/docker-compose.yml
#
# Start with: docker compose up -d
# Access Grafana at: http://${nas_ip}:3000 (admin/admin)
# Access Prometheus at: http://${nas_ip}:9090

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
EOF

    # Copy the grafana dashboard
    if [[ -f "${SCRIPT_DIR}/../grafana-dashboard.json" ]]; then
        cp "${SCRIPT_DIR}/../grafana-dashboard.json" "$monitoring_dir/"
    fi

    gum style --foreground 46 "✓ Monitoring config created in output/monitoring/"
}

# Main setup function
run_jellyfin_setup() {
    local mac_ip="$1"
    local mac_user="$2"
    local nas_ip="$3"
    local nas_user="${4:-admin}"
    local cache_path="${5:-/volume1/docker/jellyfin/cache}"
    local jellyfin_config="${6:-/volume1/docker/jellyfin}"

    # Create output directory
    mkdir -p "$OUTPUT_DIR"

    gum style --foreground 212 "Generating configuration files..."
    echo ""

    generate_ssh_key
    create_rffmpeg_config "$mac_ip" "$mac_user"
    create_docker_compose "$mac_ip" "$nas_ip" "$cache_path" "$jellyfin_config"
    create_monitoring_config "$mac_ip" "$nas_ip"
    create_readme "$mac_ip" "$mac_user" "$nas_ip" "$nas_user" "$cache_path" "$jellyfin_config"

    show_summary "$mac_ip" "$mac_user" "$nas_ip" "$nas_user" "$jellyfin_config" "$cache_path"
}
